LANGUAGES = {
    "English": "en",
    "Hindi": "hi",
    "Bengali": "bn",
    "Urdu": "ur",
    "Arabic": "ar",
    "Spanish": "es",
    "French": "fr",
    "German": "de",
    "Italian": "it",
    "Portuguese": "pt",
    "Portuguese (Brazil)": "pt-BR",
    "Russian": "ru",
    "Japanese": "ja",
    "Korean": "ko",
    "Chinese (Simplified)": "zh-Hans",
    "Chinese (Traditional)": "zh-Hant",
    "Turkish": "tr",
    "Dutch": "nl",
    "Swedish": "sv",
    "Danish": "da",
    "Finnish": "fi",
    "Norwegian": "nb",
    "Polish": "pl",
    "Czech": "cs",
    "Romanian": "ro",
    "Greek": "el",
    "Hebrew": "he",
    "Thai": "th",
    "Vietnamese": "vi",
    "Indonesian": "id",
    "Malay": "ms",
    "Tagalog": "tl",
    "Swahili": "sw",
    "Irish": "ga",
    "Hungarian": "hu",
    "Ukrainian": "uk",
    "Persian": "fa",
    "Bulgarian": "bg",
    "Catalan": "ca",
    "Basque": "eu",
    "Estonian": "et",
    "Latvian": "lv",
    "Lithuanian": "lt",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Albanian": "sq",
    "Azerbaijani": "az",
    "Kyrgyz": "ky",
}